export const blogdata=[
    {
        id:1,
        blogTitle:"A blog about sports",
        author:"Admin",
        image:"https://static01.nyt.com/images/2019/04/16/sports/16onsoccerweb-2/merlin_153612873_5bb119b9-8972-4087-b4fd-371cab8c5ba2-superJumbo.jpg",
        catagorie:"sports",
        blogContent:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quisquam neque incidunt ea nisi, possimus, illum provident eligendi officiis illo fugiat enim ab sequi sed tenetur quas error. Molestiae magni, ratione cumque, hic aspernatur est porro ipsam quod facere delectus harum saepe deserunt similique. Ad ipsum rem tempora vitae, consectetur quaerat reiciendis! Perspiciatis assumenda labore beatae doloribus aliquam nemo modi, earum officia sapiente laudantium, iure officiis magnam esse dicta suscipit! Maiores ab itaque eveniet tenetur, in nihil eaque dolores veritatis cumque, voluptatibus omnis! Fugit consequuntur ipsam architecto cum nemo, inventore perferendis unde perspiciatis facere illo quas quos! Aliquid fugit incidunt explicabo mollitia molestiae quisquam minima quam assumenda, rem modi! Placeat maxime repellendus non tempora blanditiis ratione incidunt inventore, quia, sint voluptates, voluptatibus natus sed quaerat nemo? Sunt provident aspernatur porro totam ullam amet ea reiciendis molestiae. Rerum, sapiente! Maiores, deserunt hic harum officiis adipisci soluta blanditiis eveniet, ex dicta inventore aliquid deleniti numquam est, sint exercitationem. Ea voluptates vitae veritatis numquam, quia hic, eligendi sint aut dolorum praesentium dicta repellat distinctio deserunt! Amet ipsam officiis libero quaerat enim vel accusantium non fugiat, minima aliquam quo magni eos, animi ex rerum quod soluta nesciunt nulla incidunt reprehenderit ratione ullam. Voluptates debitis eius saepe numquam id similique veritatis? A porro dolor sapiente quas id distinctio, commodi voluptatibus dolores eaque nihil explicabo dolorum nemo officiis perspiciatis excepturi quis. Voluptates porro quidem ex repellat iure neque adipisci perspiciatis possimus! Voluptas, delectus dolores. Vel, quo. Sit repellendus consequuntur quisquam deserunt molestias porro voluptas, quos ipsa dolorem eveniet nihil modi quas voluptatem dicta atque voluptate dolore ad perspiciatis voluptatibus dolor maiores suscipit pariatur non. Aliquam minus ratione excepturi labore, suscipit eos doloribus magni similique iste animi alias illum. Iure amet aperiam dolores, maiores ipsam voluptates porro laborum corrupti impedit, odit nisi at suscipit consectetur esse praesentium."

    },
    {
        id:2,
        blogTitle:"A blog about Technology",
        author:"Admin",
        image:"https://importanceoftechnology.net/wp-content/uploads/2020/05/Physiofusion-1024x819-2-950x760-1.jpg",
        catagorie:"technology",
        blogContent:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quisquam neque incidunt ea nisi, possimus, illum provident eligendi officiis illo fugiat enim ab sequi sed tenetur quas error. Molestiae magni, ratione cumque, hic aspernatur est porro ipsam quod facere delectus harum saepe deserunt similique. Ad ipsum rem tempora vitae, consectetur quaerat reiciendis! Perspiciatis assumenda labore beatae doloribus aliquam nemo modi, earum officia sapiente laudantium, iure officiis magnam esse dicta suscipit! Maiores ab itaque eveniet tenetur, in nihil eaque dolores veritatis cumque, voluptatibus omnis! Fugit consequuntur ipsam architecto cum nemo, inventore perferendis unde perspiciatis facere illo quas quos! Aliquid fugit incidunt explicabo mollitia molestiae quisquam minima quam assumenda, rem modi! Placeat maxime repellendus non tempora blanditiis ratione incidunt inventore, quia, sint voluptates, voluptatibus natus sed quaerat nemo? Sunt provident aspernatur porro totam ullam amet ea reiciendis molestiae. Rerum, sapiente! Maiores, deserunt hic harum officiis adipisci soluta blanditiis eveniet, ex dicta inventore aliquid deleniti numquam est, sint exercitationem. Ea voluptates vitae veritatis numquam, quia hic, eligendi sint aut dolorum praesentium dicta repellat distinctio deserunt! Amet ipsam officiis libero quaerat enim vel accusantium non fugiat, minima aliquam quo magni eos, animi ex rerum quod soluta nesciunt nulla incidunt reprehenderit ratione ullam. Voluptates debitis eius saepe numquam id similique veritatis? A porro dolor sapiente quas id distinctio, commodi voluptatibus dolores eaque nihil explicabo dolorum nemo officiis perspiciatis excepturi quis. Voluptates porro quidem ex repellat iure neque adipisci perspiciatis possimus! Voluptas, delectus dolores. Vel, quo. Sit repellendus consequuntur quisquam deserunt molestias porro voluptas, quos ipsa dolorem eveniet nihil modi quas voluptatem dicta atque voluptate dolore ad perspiciatis voluptatibus dolor maiores suscipit pariatur non. Aliquam minus ratione excepturi labore, suscipit eos doloribus magni similique iste animi alias illum. Iure amet aperiam dolores, maiores ipsam voluptates porro laborum corrupti impedit, odit nisi at suscipit consectetur esse praesentium."

    },
    {
        id:3,
        blogTitle:"A blog about Movie",
        author:"Admin",
        image:"https://www.pinkvilla.com/files/styles/amp_metadata_content_image/public/jawan-posters.jpg",
        catagorie:"movie",
        blogContent:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quisquam neque incidunt ea nisi, possimus, illum provident eligendi officiis illo fugiat enim ab sequi sed tenetur quas error. Molestiae magni, ratione cumque, hic aspernatur est porro ipsam quod facere delectus harum saepe deserunt similique. Ad ipsum rem tempora vitae, consectetur quaerat reiciendis! Perspiciatis assumenda labore beatae doloribus aliquam nemo modi, earum officia sapiente laudantium, iure officiis magnam esse dicta suscipit! Maiores ab itaque eveniet tenetur, in nihil eaque dolores veritatis cumque, voluptatibus omnis! Fugit consequuntur ipsam architecto cum nemo, inventore perferendis unde perspiciatis facere illo quas quos! Aliquid fugit incidunt explicabo mollitia molestiae quisquam minima quam assumenda, rem modi! Placeat maxime repellendus non tempora blanditiis ratione incidunt inventore, quia, sint voluptates, voluptatibus natus sed quaerat nemo? Sunt provident aspernatur porro totam ullam amet ea reiciendis molestiae. Rerum, sapiente! Maiores, deserunt hic harum officiis adipisci soluta blanditiis eveniet, ex dicta inventore aliquid deleniti numquam est, sint exercitationem. Ea voluptates vitae veritatis numquam, quia hic, eligendi sint aut dolorum praesentium dicta repellat distinctio deserunt! Amet ipsam officiis libero quaerat enim vel accusantium non fugiat, minima aliquam quo magni eos, animi ex rerum quod soluta nesciunt nulla incidunt reprehenderit ratione ullam. Voluptates debitis eius saepe numquam id similique veritatis? A porro dolor sapiente quas id distinctio, commodi voluptatibus dolores eaque nihil explicabo dolorum nemo officiis perspiciatis excepturi quis. Voluptates porro quidem ex repellat iure neque adipisci perspiciatis possimus! Voluptas, delectus dolores. Vel, quo. Sit repellendus consequuntur quisquam deserunt molestias porro voluptas, quos ipsa dolorem eveniet nihil modi quas voluptatem dicta atque voluptate dolore ad perspiciatis voluptatibus dolor maiores suscipit pariatur non. Aliquam minus ratione excepturi labore, suscipit eos doloribus magni similique iste animi alias illum. Iure amet aperiam dolores, maiores ipsam voluptates porro laborum corrupti impedit, odit nisi at suscipit consectetur esse praesentium."

    },
    {
        id:4,
        blogTitle:"A blog about Buisness",
        author:"Admin",
        image:"https://www.primeum.com/hubfs/D%C3%A9finition-performance-commerciale.jpg",
        catagorie:"buisness",
        blogContent:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quisquam neque incidunt ea nisi, possimus, illum provident eligendi officiis illo fugiat enim ab sequi sed tenetur quas error. Molestiae magni, ratione cumque, hic aspernatur est porro ipsam quod facere delectus harum saepe deserunt similique. Ad ipsum rem tempora vitae, consectetur quaerat reiciendis! Perspiciatis assumenda labore beatae doloribus aliquam nemo modi, earum officia sapiente laudantium, iure officiis magnam esse dicta suscipit! Maiores ab itaque eveniet tenetur, in nihil eaque dolores veritatis cumque, voluptatibus omnis! Fugit consequuntur ipsam architecto cum nemo, inventore perferendis unde perspiciatis facere illo quas quos! Aliquid fugit incidunt explicabo mollitia molestiae quisquam minima quam assumenda, rem modi! Placeat maxime repellendus non tempora blanditiis ratione incidunt inventore, quia, sint voluptates, voluptatibus natus sed quaerat nemo? Sunt provident aspernatur porro totam ullam amet ea reiciendis molestiae. Rerum, sapiente! Maiores, deserunt hic harum officiis adipisci soluta blanditiis eveniet, ex dicta inventore aliquid deleniti numquam est, sint exercitationem. Ea voluptates vitae veritatis numquam, quia hic, eligendi sint aut dolorum praesentium dicta repellat distinctio deserunt! Amet ipsam officiis libero quaerat enim vel accusantium non fugiat, minima aliquam quo magni eos, animi ex rerum quod soluta nesciunt nulla incidunt reprehenderit ratione ullam. Voluptates debitis eius saepe numquam id similique veritatis? A porro dolor sapiente quas id distinctio, commodi voluptatibus dolores eaque nihil explicabo dolorum nemo officiis perspiciatis excepturi quis. Voluptates porro quidem ex repellat iure neque adipisci perspiciatis possimus! Voluptas, delectus dolores. Vel, quo. Sit repellendus consequuntur quisquam deserunt molestias porro voluptas, quos ipsa dolorem eveniet nihil modi quas voluptatem dicta atque voluptate dolore ad perspiciatis voluptatibus dolor maiores suscipit pariatur non. Aliquam minus ratione excepturi labore, suscipit eos doloribus magni similique iste animi alias illum. Iure amet aperiam dolores, maiores ipsam voluptates porro laborum corrupti impedit, odit nisi at suscipit consectetur esse praesentium."

    },
    {
        id:5,
        blogTitle:"A blog about Discovery",
        author:"Admin",
        image:"https://mars.nasa.gov/layout/mars2020/images/PIA23764-RoverNamePlateonMars-web.jpg",
        catagorie:"discovery",
        blogContent:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quisquam neque incidunt ea nisi, possimus, illum provident eligendi officiis illo fugiat enim ab sequi sed tenetur quas error. Molestiae magni, ratione cumque, hic aspernatur est porro ipsam quod facere delectus harum saepe deserunt similique. Ad ipsum rem tempora vitae, consectetur quaerat reiciendis! Perspiciatis assumenda labore beatae doloribus aliquam nemo modi, earum officia sapiente laudantium, iure officiis magnam esse dicta suscipit! Maiores ab itaque eveniet tenetur, in nihil eaque dolores veritatis cumque, voluptatibus omnis! Fugit consequuntur ipsam architecto cum nemo, inventore perferendis unde perspiciatis facere illo quas quos! Aliquid fugit incidunt explicabo mollitia molestiae quisquam minima quam assumenda, rem modi! Placeat maxime repellendus non tempora blanditiis ratione incidunt inventore, quia, sint voluptates, voluptatibus natus sed quaerat nemo? Sunt provident aspernatur porro totam ullam amet ea reiciendis molestiae. Rerum, sapiente! Maiores, deserunt hic harum officiis adipisci soluta blanditiis eveniet, ex dicta inventore aliquid deleniti numquam est, sint exercitationem. Ea voluptates vitae veritatis numquam, quia hic, eligendi sint aut dolorum praesentium dicta repellat distinctio deserunt! Amet ipsam officiis libero quaerat enim vel accusantium non fugiat, minima aliquam quo magni eos, animi ex rerum quod soluta nesciunt nulla incidunt reprehenderit ratione ullam. Voluptates debitis eius saepe numquam id similique veritatis? A porro dolor sapiente quas id distinctio, commodi voluptatibus dolores eaque nihil explicabo dolorum nemo officiis perspiciatis excepturi quis. Voluptates porro quidem ex repellat iure neque adipisci perspiciatis possimus! Voluptas, delectus dolores. Vel, quo. Sit repellendus consequuntur quisquam deserunt molestias porro voluptas, quos ipsa dolorem eveniet nihil modi quas voluptatem dicta atque voluptate dolore ad perspiciatis voluptatibus dolor maiores suscipit pariatur non. Aliquam minus ratione excepturi labore, suscipit eos doloribus magni similique iste animi alias illum. Iure amet aperiam dolores, maiores ipsam voluptates porro laborum corrupti impedit, odit nisi at suscipit consectetur esse praesentium."

    },
    {
        id:6,
        blogTitle:"A blog about Technology",
        author:"Admin",
        image:"https://importanceoftechnology.net/wp-content/uploads/2020/05/Physiofusion-1024x819-2-950x760-1.jpg",
        catagorie:"technology",
        blogContent:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quisquam neque incidunt ea nisi, possimus, illum provident eligendi officiis illo fugiat enim ab sequi sed tenetur quas error. Molestiae magni, ratione cumque, hic aspernatur est porro ipsam quod facere delectus harum saepe deserunt similique. Ad ipsum rem tempora vitae, consectetur quaerat reiciendis! Perspiciatis assumenda labore beatae doloribus aliquam nemo modi, earum officia sapiente laudantium, iure officiis magnam esse dicta suscipit! Maiores ab itaque eveniet tenetur, in nihil eaque dolores veritatis cumque, voluptatibus omnis! Fugit consequuntur ipsam architecto cum nemo, inventore perferendis unde perspiciatis facere illo quas quos! Aliquid fugit incidunt explicabo mollitia molestiae quisquam minima quam assumenda, rem modi! Placeat maxime repellendus non tempora blanditiis ratione incidunt inventore, quia, sint voluptates, voluptatibus natus sed quaerat nemo? Sunt provident aspernatur porro totam ullam amet ea reiciendis molestiae. Rerum, sapiente! Maiores, deserunt hic harum officiis adipisci soluta blanditiis eveniet, ex dicta inventore aliquid deleniti numquam est, sint exercitationem. Ea voluptates vitae veritatis numquam, quia hic, eligendi sint aut dolorum praesentium dicta repellat distinctio deserunt! Amet ipsam officiis libero quaerat enim vel accusantium non fugiat, minima aliquam quo magni eos, animi ex rerum quod soluta nesciunt nulla incidunt reprehenderit ratione ullam. Voluptates debitis eius saepe numquam id similique veritatis? A porro dolor sapiente quas id distinctio, commodi voluptatibus dolores eaque nihil explicabo dolorum nemo officiis perspiciatis excepturi quis. Voluptates porro quidem ex repellat iure neque adipisci perspiciatis possimus! Voluptas, delectus dolores. Vel, quo. Sit repellendus consequuntur quisquam deserunt molestias porro voluptas, quos ipsa dolorem eveniet nihil modi quas voluptatem dicta atque voluptate dolore ad perspiciatis voluptatibus dolor maiores suscipit pariatur non. Aliquam minus ratione excepturi labore, suscipit eos doloribus magni similique iste animi alias illum. Iure amet aperiam dolores, maiores ipsam voluptates porro laborum corrupti impedit, odit nisi at suscipit consectetur esse praesentium."

    },
    {
        id:7,
        blogTitle:"A blog about Technology",
        author:"Admin",
        image:"https://groupdiscussion.gkbymrdj.com/wp-content/uploads/2021/09/technology-esports.jpg",
        catagorie:"technology",
        blogContent:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quisquam neque incidunt ea nisi, possimus, illum provident eligendi officiis illo fugiat enim ab sequi sed tenetur quas error. Molestiae magni, ratione cumque, hic aspernatur est porro ipsam quod facere delectus harum saepe deserunt similique. Ad ipsum rem tempora vitae, consectetur quaerat reiciendis! Perspiciatis assumenda labore beatae doloribus aliquam nemo modi, earum officia sapiente laudantium, iure officiis magnam esse dicta suscipit! Maiores ab itaque eveniet tenetur, in nihil eaque dolores veritatis cumque, voluptatibus omnis! Fugit consequuntur ipsam architecto cum nemo, inventore perferendis unde perspiciatis facere illo quas quos! Aliquid fugit incidunt explicabo mollitia molestiae quisquam minima quam assumenda, rem modi! Placeat maxime repellendus non tempora blanditiis ratione incidunt inventore, quia, sint voluptates, voluptatibus natus sed quaerat nemo? Sunt provident aspernatur porro totam ullam amet ea reiciendis molestiae. Rerum, sapiente! Maiores, deserunt hic harum officiis adipisci soluta blanditiis eveniet, ex dicta inventore aliquid deleniti numquam est, sint exercitationem. Ea voluptates vitae veritatis numquam, quia hic, eligendi sint aut dolorum praesentium dicta repellat distinctio deserunt! Amet ipsam officiis libero quaerat enim vel accusantium non fugiat, minima aliquam quo magni eos, animi ex rerum quod soluta nesciunt nulla incidunt reprehenderit ratione ullam. Voluptates debitis eius saepe numquam id similique veritatis? A porro dolor sapiente quas id distinctio, commodi voluptatibus dolores eaque nihil explicabo dolorum nemo officiis perspiciatis excepturi quis. Voluptates porro quidem ex repellat iure neque adipisci perspiciatis possimus! Voluptas, delectus dolores. Vel, quo. Sit repellendus consequuntur quisquam deserunt molestias porro voluptas, quos ipsa dolorem eveniet nihil modi quas voluptatem dicta atque voluptate dolore ad perspiciatis voluptatibus dolor maiores suscipit pariatur non. Aliquam minus ratione excepturi labore, suscipit eos doloribus magni similique iste animi alias illum. Iure amet aperiam dolores, maiores ipsam voluptates porro laborum corrupti impedit, odit nisi at suscipit consectetur esse praesentium."

    }, 
     {
        id:8,
        blogTitle:"A blog about Movie",
        author:"Admin",
        image:"https://images.news18.com/ibnlive/uploads/2022/01/hrithik-roshan-vikram-vedha.jpg",
        catagorie:"movie",
        blogContent:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quisquam neque incidunt ea nisi, possimus, illum provident eligendi officiis illo fugiat enim ab sequi sed tenetur quas error. Molestiae magni, ratione cumque, hic aspernatur est porro ipsam quod facere delectus harum saepe deserunt similique. Ad ipsum rem tempora vitae, consectetur quaerat reiciendis! Perspiciatis assumenda labore beatae doloribus aliquam nemo modi, earum officia sapiente laudantium, iure officiis magnam esse dicta suscipit! Maiores ab itaque eveniet tenetur, in nihil eaque dolores veritatis cumque, voluptatibus omnis! Fugit consequuntur ipsam architecto cum nemo, inventore perferendis unde perspiciatis facere illo quas quos! Aliquid fugit incidunt explicabo mollitia molestiae quisquam minima quam assumenda, rem modi! Placeat maxime repellendus non tempora blanditiis ratione incidunt inventore, quia, sint voluptates, voluptatibus natus sed quaerat nemo? Sunt provident aspernatur porro totam ullam amet ea reiciendis molestiae. Rerum, sapiente! Maiores, deserunt hic harum officiis adipisci soluta blanditiis eveniet, ex dicta inventore aliquid deleniti numquam est, sint exercitationem. Ea voluptates vitae veritatis numquam, quia hic, eligendi sint aut dolorum praesentium dicta repellat distinctio deserunt! Amet ipsam officiis libero quaerat enim vel accusantium non fugiat, minima aliquam quo magni eos, animi ex rerum quod soluta nesciunt nulla incidunt reprehenderit ratione ullam. Voluptates debitis eius saepe numquam id similique veritatis? A porro dolor sapiente quas id distinctio, commodi voluptatibus dolores eaque nihil explicabo dolorum nemo officiis perspiciatis excepturi quis. Voluptates porro quidem ex repellat iure neque adipisci perspiciatis possimus! Voluptas, delectus dolores. Vel, quo. Sit repellendus consequuntur quisquam deserunt molestias porro voluptas, quos ipsa dolorem eveniet nihil modi quas voluptatem dicta atque voluptate dolore ad perspiciatis voluptatibus dolor maiores suscipit pariatur non. Aliquam minus ratione excepturi labore, suscipit eos doloribus magni similique iste animi alias illum. Iure amet aperiam dolores, maiores ipsam voluptates porro laborum corrupti impedit, odit nisi at suscipit consectetur esse praesentium."

    },
]

